### ISSUE TITLE
matplotlib port?

### ISSUE THREAD

**Issue by podopie** [timcdlucas/palettetown#13]
i'd love to have these colormaps available in python

**Comment by timcdlucas** [comment]
Yeah I thought about it. I don't use python much so it would be finding time to learn how to make a python package first.

If you make python packages feel free to just pull the data out.

**Comment by podopie** [comment]
cool, I might do it this weekend then! should be a fun project.

**Comment by timcdlucas** [comment]
Awesome! Let me know how it goes.

The colour data is in `R/sysdata.rda`. No idea if you're familiar with R, but if you are you should be able to open that and write out to something more python friendly.

**Comment by podopie** [comment]
the rda is fine

**Comment by timcdlucas** [comment]
Closing this as I'm not going to do anything about it. Let me know if you make the package. I'll link it and that.
